import Link from 'next/link';

export default function LegalPage() {
    return (
        <div className="min-h-screen bg-bg-primary text-text-primary px-6 py-20">
            <div className="container mx-auto max-w-3xl">
                <Link href="/" className="inline-block mb-12 text-primary hover:underline">← Back to Home</Link>

                <h1 className="text-5xl font-black mb-8">Legal & Methodology Notice</h1>
                <p className="text-xl text-text-secondary mb-12 italic">
                    GhostJob is a data integrity platform designed to provide transparency in the hiring market.
                    Please read how we handle data and liability.
                </p>

                <div className="space-y-12">
                    <section>
                        <h2 className="text-2xl font-bold mb-4 text-primary">1. Nature of the Service</h2>
                        <p className="text-text-secondary leading-relaxed mb-4">
                            GhostJob provides automated analysis of job postings based on patterns found in publicly available data and user-reported outcomes.
                            The &quot;Ghost Transparency Score™&quot; and individual analysis results are <strong>informational opinions</strong> generated by algorithmic processing of
                            content provided by job boards and community members.
                        </p>
                        <div className="p-4 bg-danger/10 border border-danger/20 rounded-xl text-sm font-semibold">
                            ⚠️ GhostJob does not make accusations of fraud. Our scores represent statistical probability and pattern matching, not legal verdicts.
                        </div>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4 text-primary">2. Platform vs. Publisher (Safe Harbor)</h2>
                        <p className="text-text-secondary leading-relaxed">
                            GhostJob acts as a **Platform** for User-Generated Content (UGC) under established safe harbor frameworks (including GDPR compliance in the EU).
                            Outcome reports (responses, interviews, ghosts) are provided anonymously by our community. We do not edit user reports, but we do provide
                            mechanisms for companies to verify and respond to their market data.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4 text-primary">3. Company Right of Reply</h2>
                        <p className="text-text-secondary leading-relaxed">
                            We believe in fair transparency. Any company listed on GhostJob has the right to:
                        </p>
                        <ul className="list-disc list-inside mt-4 space-y-2 text-text-secondary">
                            <li>Request verification of their data signals.</li>
                            <li>Provide official responses to transparency scores.</li>
                            <li>Access a dashboard to monitor their hiring reputation (B2B tier).</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4 text-primary">4. Data Accuracy</h2>
                        <p className="text-text-secondary leading-relaxed">
                            Job market data is dynamic. Scores can change daily based on new application outcomes reported by our users. While we use
                            advanced AI (Pro v3.5) to minimize false positives, we provide no guarantee of absolute accuracy for any single job posting analysis.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold mb-4 text-primary">5. Contact & Disputes</h2>
                        <p className="text-text-secondary leading-relaxed">
                            For data verification requests or legal inquiries, please contact: <br />
                            <span className="text-white font-mono">legal@ghostjob.app</span>
                        </p>
                    </section>
                </div>

                <footer className="mt-20 pt-12 border-t border-gray-800 text-sm text-text-secondary">
                    © 2026 GhostJob Transparency Infrastructure. All rights reserved.
                </footer>
            </div>
        </div>
    );
}
