import Link from 'next/link';

export default function LegalDisclaimer() {
    return (
        <div className="mt-12 pt-8 border-t border-white/5 text-[10px] text-text-secondary leading-relaxed max-w-2xl mx-auto text-center italic">
            <p className="mb-2">
                <strong>Disclaimer:</strong> This &quot;Ghost Transparency Score™&quot; is an automated analysis generated by the GhostJob Pro v3.5 AI Engine.
                It is based on a statistical interpretation of the job posting text, historical market patterns, and community reports.
            </p>
            <p>
                This result constitutes an informational opinion and does not represent a legal find of fraud or scam.
                Companies are encouraged to verify their data. <Link href="/legal" className="text-primary hover:underline">Read our full Methodology & Legal Notice</Link>.
            </p>
        </div>
    );
}
